#!/usr/bin/env node

require('dotenv').config();

const WebSocket = require('ws');
const fs = require('fs');
const path = require('path');

const HA_HOST = '192.168.0.110';
const HA_PORT = 8123;
const HA_TOKEN = process.env.HA_TOKEN;

if (!HA_TOKEN) {
  console.error('Error: HA_TOKEN environment variable is not set');
  console.error('Please set it with: export HA_TOKEN="your_token_here"');
  process.exit(1);
}

let messageId = 1;

async function sendWebSocketCommand(ws, command) {
  return new Promise((resolve, reject) => {
    const id = messageId++;
    const handler = (data) => {
      try {
        const message = JSON.parse(data);
        if (message.id === id) {
          ws.removeListener('message', handler);
          if (message.success === false) {
            reject(new Error(message.error?.message || 'Command failed'));
          } else {
            resolve(message.result);
          }
        }
      } catch (e) {
        // Ignore parse errors for other messages
      }
    };

    ws.on('message', handler);
    ws.send(JSON.stringify({ id, ...command }));

    // Timeout after 10 seconds
    setTimeout(() => {
      ws.removeListener('message', handler);
      reject(new Error('Command timeout'));
    }, 10000);
  });
}

async function connectWebSocket() {
  return new Promise((resolve, reject) => {
    const ws = new WebSocket(`ws://${HA_HOST}:${HA_PORT}/api/websocket`);

    ws.on('open', () => {
      ws.once('message', (data) => {
        const message = JSON.parse(data);
        if (message.type === 'auth_required') {
          ws.send(JSON.stringify({
            type: 'auth',
            access_token: HA_TOKEN
          }));

          ws.once('message', (authData) => {
            const authMessage = JSON.parse(authData);
            if (authMessage.type === 'auth_ok') {
              resolve(ws);
            } else {
              reject(new Error('Authentication failed'));
            }
          });
        }
      });
    });

    ws.on('error', (error) => {
      reject(error);
    });
  });
}

async function main() {
  let ws;
  try {
    console.log('Connecting to Home Assistant WebSocket...');
    ws = await connectWebSocket();
    console.log('Connected successfully!');

    console.log('Fetching areas...');
    const areas = await sendWebSocketCommand(ws, {
      type: 'config/area_registry/list'
    });

    console.log('Fetching devices...');
    const devices = await sendWebSocketCommand(ws, {
      type: 'config/device_registry/list'
    });

    console.log('Fetching entities...');
    const entities = await sendWebSocketCommand(ws, {
      type: 'config/entity_registry/list'
    });

    // Create a map of device_id to area_id
    const deviceToArea = {};
    devices.forEach(device => {
      if (device.area_id) {
        deviceToArea[device.id] = device.area_id;
      }
    });

    // Create a map of area_id to entity IDs
    const areaMap = {};

    // Initialize areas
    areas.forEach(area => {
      areaMap[area.area_id] = [];
    });

    // Add entities to their areas
    entities.forEach(entity => {
      let areaId = entity.area_id;

      // If entity doesn't have area_id, get it from its device
      if (!areaId && entity.device_id && deviceToArea[entity.device_id]) {
        areaId = deviceToArea[entity.device_id];
      }

      if (areaId && areaMap[areaId]) {
        areaMap[areaId].push(entity.entity_id);
      }
    });

    // Generate YAML content
    let yamlContent = '# Areas to Entity IDs mapping\n';
    yamlContent += '# Auto-generated by: npm run update:areas\n';
    yamlContent += `# Generated at: ${new Date().toISOString()}\n\n`;

    // Sort by area_id
    const sortedAreaIds = Object.keys(areaMap).sort();

    sortedAreaIds.forEach(areaId => {
      const entityIds = areaMap[areaId].sort();
      yamlContent += `${areaId}:\n`;

      if (entityIds.length > 0) {
        entityIds.forEach(entityId => {
          yamlContent += `  - ${entityId}\n`;
        });
      } else {
        yamlContent += `  []\n`;
      }

      yamlContent += '\n';
    });

    // Write to file
    const outputPath = path.join(__dirname, '..', 'state', 'areas.yaml');
    fs.writeFileSync(outputPath, yamlContent, 'utf8');

    const totalEntities = Object.values(areaMap).reduce((sum, ids) => sum + ids.length, 0);
    console.log(`\n✓ Successfully wrote ${sortedAreaIds.length} areas to ${outputPath}`);
    console.log(`  Total entities mapped: ${totalEntities}`);

  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  } finally {
    if (ws) {
      ws.close();
    }
  }
}

main();
