#!/usr/bin/env node

require('dotenv').config();

const http = require('http');
const fs = require('fs');
const path = require('path');

const HA_HOST = '192.168.0.110';
const HA_PORT = 8123;
const HA_TOKEN = process.env.HA_TOKEN;

if (!HA_TOKEN) {
  console.error('Error: HA_TOKEN environment variable is not set');
  console.error('Please set it with: export HA_TOKEN="your_token_here"');
  process.exit(1);
}

async function fetchStates() {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: HA_HOST,
      port: HA_PORT,
      path: '/api/states',
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${HA_TOKEN}`,
        'Content-Type': 'application/json'
      }
    };

    const req = http.request(options, (res) => {
      let data = '';

      res.on('data', (chunk) => {
        data += chunk;
      });

      res.on('end', () => {
        if (res.statusCode === 200) {
          try {
            resolve(JSON.parse(data));
          } catch (e) {
            reject(new Error(`Failed to parse JSON: ${e.message}`));
          }
        } else {
          reject(new Error(`HTTP ${res.statusCode}: ${data}`));
        }
      });
    });

    req.on('error', (e) => {
      reject(e);
    });

    req.end();
  });
}

function simplifyState(entity) {
  const domain = entity.entity_id.split('.')[0];
  const state = entity.state;
  const attrs = entity.attributes || {};

  // Handle different entity types
  switch (domain) {
    case 'light':
      if (state === 'off') {
        return 'off';
      }
      // Return brightness if available (0-255), otherwise just 'on'
      return attrs.brightness !== undefined ? attrs.brightness : 'on';

    case 'switch':
    case 'binary_sensor':
    case 'input_boolean':
      return state;

    case 'sensor':
    case 'number':
    case 'input_number':
      // Return numeric value if it's a number, otherwise the state
      const numValue = parseFloat(state);
      return isNaN(numValue) ? state : numValue;

    case 'climate':
      // Return object with key info
      return {
        state: state,
        temperature: attrs.temperature,
        current_temperature: attrs.current_temperature
      };

    case 'cover':
      // Return position if available, otherwise state
      return attrs.current_position !== undefined ? attrs.current_position : state;

    case 'media_player':
      return state;

    case 'lock':
      return state;

    case 'fan':
      if (state === 'off') {
        return 'off';
      }
      return attrs.percentage !== undefined ? attrs.percentage : 'on';

    default:
      // For everything else, just return the state
      return state;
  }
}

async function main() {
  try {
    console.log('Fetching entity states from Home Assistant...');
    const states = await fetchStates();

    // Create state map
    const stateMap = {};

    states.forEach(entity => {
      stateMap[entity.entity_id] = simplifyState(entity);
    });

    // Generate YAML content
    let yamlContent = '# Entity States\n';
    yamlContent += '# Auto-generated by: npm run update:state\n';
    yamlContent += `# Generated at: ${new Date().toISOString()}\n\n`;

    // Sort entity IDs
    const sortedEntityIds = Object.keys(stateMap).sort();

    sortedEntityIds.forEach(entityId => {
      const state = stateMap[entityId];

      if (typeof state === 'object') {
        yamlContent += `${entityId}:\n`;
        Object.entries(state).forEach(([key, value]) => {
          if (value !== undefined && value !== null) {
            yamlContent += `  ${key}: ${value}\n`;
          }
        });
      } else {
        yamlContent += `${entityId}: ${state}\n`;
      }
    });

    // Write to file
    const outputPath = path.join(__dirname, '..', 'state', 'state.yaml');
    fs.writeFileSync(outputPath, yamlContent, 'utf8');

    console.log(`\n✓ Successfully wrote ${sortedEntityIds.length} entity states to ${outputPath}`);

  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

main();
